###

POST http://127.0.0.1:5003/transactions/insert
Content-Type: application/json

{ 
    "userID": 33,
    "accountID": 621156213,
    "receivingaccountID": 1238728379123,
    "date": "2022-11-17T06:21:00.000Z",
    "transactionamount": 23072,
    "comment": "comment"
}

###

POST http://127.0.0.1:5003/user/bankaccounts
Content-Type: application/json

{
    "userid": 10
}

###

POST http://127.0.0.1:5003/user/accountid
Content-Type: application/json

{
    "userid": 1
}

###

DELETE http://127.0.0.1:5003/transactions/delete
Content-Type: application/json

{
    "transactionID": [10, 11] 
}